import { TListElement } from './stacks.types';

const foundlingStack: TListElement[] = [
  {
    word: 'foundling',
    adjective: [],
    adverb: [],
    noun: ['abandoned infant, discovered cared others.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'foundry',
    adjective: [],
    adverb: [],
    noun: ['factory metal, melted, moulded.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fount',
    adjective: [],
    adverb: [],
    noun: ['source knowledge, stories.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fountain',
    adjective: [],
    adverb: [],
    noun: [
      'jet water;',
      'structure;',
      'natural spring water;',
      'source (physical abstract).',
    ],
    verb: ['intransitive: spurt/cascade like fountain.'],
    modification: [],
    idiom: [],
    image: '/images/fountain.png',
  },
  {
    word: 'four',
    adjective: [],
    adverb: ['on all fours: on hands knees.'],
    noun: [],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'foursome',
    adjective: [],
    adverb: [],
    noun: ['group, four persons.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fourteen',
    adjective: [],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['fourteenth.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fourth',
    adjective: [],
    adverb: [],
    noun: [
      'a quarter;',
      'music;',
      'chord, four consecutive notes;',
      'separated.',
    ],
    verb: [],
    modification: ['fourthly.'],
    idiom: [],
    image: null,
  },
  // picture #2
  {
    word: 'fowl',
    adjective: [],
    adverb: [],
    noun: ['domestic bird;', 'flesh food.'],
    verb: [],
    modification: [],
    idiom: [],
    image: '/images/fowl.png',
  },
  {
    word: 'fox',
    adjective: [],
    adverb: [],
    noun: ['mammals;', 'fur;', 'cunning, sly person;', 'attractive woman.'],
    verb: ['transitive: deceive, baffle.'],
    modification: ['foxlike.'],
    idiom: [],
    image: '/images/fox.png',
  },
  {
    word: 'foxglove',
    adjective: [],
    adverb: [],
    noun: ['plant.'],
    verb: [],
    modification: [],
    idiom: [],
    image: '/images/foxglove.png',
  },
  {
    word: 'foxhound',
    adjective: [],
    adverb: [],
    noun: ['hound, trained hunt foxes.'],
    verb: [],
    modification: [],
    idiom: [],
    image: '/images/foxhound.png',
  },
  {
    word: 'foxtrot',
    adjective: [],
    adverb: [],
    noun: ['ballroom, dance, slow quick steps;', 'music.'],
    verb: ['perform.'],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'foyer',
    adjective: [],
    adverb: [],
    noun: ['entrance hall, area hotel, theatre, apartment, building.'],
    verb: [],
    modification: [],
    idiom: [],
    image: '/images/foyer.png',
  },
  {
    word: 'fracas',
    adjective: [],
    adverb: [],
    noun: ['noisy disturbance;', 'quarrel.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fraction',
    adjective: ['(children) quarrelsome.'],
    adverb: [],
    noun: [
      'not a whole number;',
      'small part;',
      'whole;',
      'group difficult to control.',
    ],
    verb: [],
    modification: [
      'fractional;',
      'fractionalization;',
      'fractionalize;',
      'fractionally.',
    ],
    idiom: [],
    image: null,
  },
  {
    word: 'fractious',
    adjective: [],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['fractiously;', 'fractiousness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fracture',
    adjective: [],
    adverb: [],
    noun: ['breakage, bone, cartilage;', 'result of breaking, crack, split.'],
    verb: [
      'transitive & intransitive: undergo, cause fracture;',
      'organization, abstract;',
      'split;',
      'no longer function.',
    ],
    modification: [],
    idiom: [],
    image: null,
  },
  // picture #3
  {
    word: 'fragile',
    adjective: ['easily broken;', 'vulnerable, easily destroyed.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['fragilely;', 'fragility.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fragment',
    adjective: [],
    adverb: [],
    noun: ['part broken off;', 'incomplete part;', 'remains lost whole.'],
    verb: ['break fragments.'],
    modification: ['fragmental;', 'fragmented.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fragrance',
    adjective: [],
    adverb: [],
    noun: ['sweet scent, bleasant;', 'perfume, eau de cologne.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frail',
    adjective: [],
    adverb: [],
    noun: ['(person) physically weak, delicate;', 'easily broken.'],
    verb: [],
    modification: ['frailly;', 'frailness;', 'frailty.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frame',
    adjective: [],
    adverb: [],
    noun: [
      'border, picture, window, door;',
      'structure anything, support;',
      'structure, eyeglasses;',
      'human, animal body, size structure;',
      'single image, movie;',
      'one drawings, comic strip.',
    ],
    verb: [
      'set in, provide frame;',
      'formulate idea, theory;',
      'adapt, fit;',
      'articulate (words);',
      'surround, create striking image.',
    ],
    modification: ['frameable;', 'frameless;', 'framer.'],
    idiom: [],
    image: null,
  },
  {
    word: 'framework',
    adjective: [],
    adverb: [],
    noun: ['essential supporting structure, bulding, system, vehicle, object.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'franchise',
    adjective: [],
    adverb: [],
    noun: [
      'right vote elections;',
      'authorization granted individual group, company sell its goods, services;',
      'store, restaurant, granted authorization;',
      'authorization granted individual group, sports league, own team;',
      'general title series of products.',
    ],
    verb: ['grant franchise.'],
    modification: ['franchisee;', 'franchisor.'],
    idiom: [],
    image: null,
  },
  // picture # 4
  {
    word: 'frank',
    adjective: ['candid, outspoken;', 'undisguised;', 'ingenuous.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['frankness;', 'frankly.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frankfurter',
    adjective: [],
    adverb: [],
    noun: ['seasoned smoked sausage, beef, pork.'],
    verb: [],
    modification: [],
    idiom: [],
    image: '/images/frankfurter.png',
  },
  {
    word: 'frankincense',
    adjective: [],
    adverb: [],
    noun: ['gum resin trees, burning incense.'],
    verb: [],
    modification: [],
    idiom: [],
    image: '/images/frankincense.png',
  },
  {
    word: 'frantic',
    adjective: ['widely excited, frenzied;', 'hurry, anxiety, desperate.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['frantically;', 'franticness.'],
    idiom: [],
    image: null,
  },
];
export default foundlingStack;
