import { TListElement } from './stacks.types';

const fraternalStack: TListElement[] = [
  {
    word: 'fraternal',
    adjective: [
      'of brother;',
      '(twins) separate ova, not necessarily similar;',
      'of fraternity.',
    ],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['fraternalism;', 'fraternally.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fraternity',
    adjective: [],
    adverb: [],
    noun: [
      "male student's society university;",
      'religious brotherhood;',
      'group common interests, profssional;',
      'brotherliness.',
    ],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fraternize',
    adjective: [],
    adverb: [],
    noun: [],
    verb: ['associate, make friends, when not supposed to.'],
    modification: ['fraternization.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fraud',
    adjective: [],
    adverb: [],
    noun: [
      'action deceiving in order money obtain illegaly;',
      'person, thing not what claimed, expected.',
    ],
    verb: [],
    modification: ['fraudster;', 'fraudulent.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fraught',
    adjective: [
      '(with) filled with, something undesirable;',
      'affected anxiety, distress.',
    ],
    adverb: [],
    noun: [],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frazzle',
    adjective: [],
    adverb: [],
    noun: ['exhausted state.'],
    verb: ['transitive: exhaust;', 'shrivel up burning.'],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'freak',
    adjective: [],
    adverb: [],
    noun: [
      'abnormally developed individually;',
      'bizarre occurence;',
      'unconventional person, person specified enthusiasm.',
    ],
    verb: ['behave/came behave wild/irrational way.'],
    modification: ['freakish;', 'freakishly;', 'freakishness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'freckle',
    adjective: [],
    adverb: [],
    noun: ['light brown spots skin;', 'more pronounced;', 'exposure sun.'],
    verb: ['spot freckles;', 'be freckly.'],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'free',
    adjective: [
      'not under control another;',
      'unrestricted/able more easily, not imprisoned;',
      'not subject to;',
      'costing nothing;',
      'clear of engagements, not occupied;',
      'used without restraint.',
    ],
    adverb: ['free manner;', 'without cost.'],
    noun: [],
    verb: ['make free;', 'relieve from;', 'disengage.'],
    modification: ['freely;', 'freeness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'freedom',
    adjective: [],
    adverb: [],
    noun: [
      'being free;',
      'political right act, speak, one pleases;',
      'not subject to;',
      'not imprisoned.',
    ],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'freehand',
    adjective: ['(drawing plan) done by hand without instruments.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'freehold',
    adjective: ['held by freehold;'],
    adverb: [],
    noun: [
      'permanent absolute tenure land, property freedom dispose;',
      'land, property.',
    ],
    verb: [],
    modification: ['freeholder.'],
    idiom: [],
    image: null,
  },
  {
    word: 'freelance',
    adjective: [],
    adverb: [],
    noun: [
      'person self-employed, offering services on temporary basis, particular assignments.',
    ],
    verb: ['intrasitive: act freelance.'],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'freeloader',
    adjective: [],
    adverb: [],
    noun: ['person takes advantage others generosity not give anything.'],
    verb: [],
    modification: ['freeload.'],
    idiom: [],
    image: null,
  },
  {
    word: 'freemason',
    adjective: [],
    adverb: [],
    noun: ['member international fraternity.'],
    verb: [],
    modification: ['freemasonry.'],
    idiom: [],
    image: null,
  },
  {
    word: 'freewheel',
    adjective: [],
    adverb: [],
    noun: ['wheel bicycle, revolve pedals rest;', 'bicycle pedal at rest.'],
    verb: [],
    modification: ['freewheeler.'],
    idiom: [],
    image: null,
  },
  {
    word: 'freeze',
    adjective: [],
    adverb: [],
    noun: ['state frost;', 'fixing prices, wages.'],
    verb: [
      'turn ice, solid;',
      'be cold;',
      'adhere by frost;',
      'obstructed formation of ice;',
      'preserve freezing;',
      'become motionless, fear, surprise;',
      'make (part body) insensitive anaesthetic;',
      'make(credits, assets) unrealizible;',
      'fix (prices, wages);',
      'prohibit manufacture, sale, use, development.',
    ],
    modification: ['freezable.'],
    idiom: [],
    image: null,
  },
  {
    word: 'freight',
    adjective: [],
    adverb: [],
    noun: [
      'goods transported, water, air, land;',
      'transportation;',
      'charge for.',
    ],
    verb: ['transport (goods) freight;', 'load, burden.'],
    modification: [],
    idiom: [],
    image: '/images/freight.png',
  },
  {
    word: 'freighter',
    adjective: [],
    adverb: [],
    noun: ['ship aircraft, carry freight.'],
    verb: [],
    modification: [],
    idiom: [],
    image: '/images/freighter.png',
  },
  {
    word: 'French',
    adjective: ['France people language.'],
    adverb: [],
    noun: ['language;', 'people.'],
    verb: [],
    modification: ['Frenchness.'],
    idiom: ['pardon (excuse) my French: excuse coarse language.'],
    image: null,
  },
  {
    word: 'frenetic',
    adjective: ['frantic, frenzied;', 'fast/energetic.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['frenetically.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frenzy',
    adjective: [],
    adverb: [],
    noun: ['state/period uncontrolled excitement/wild behaviour.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frequency',
    adjective: [],
    adverb: [],
    noun: [
      'commonness occurrence;',
      'state frequent;',
      'rate reccurence vibration, oscillation, cycle;',
      'cycles per second.',
    ],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frequent',
    adjective: ['occurring often succession;', 'habitual.'],
    adverb: [],
    noun: [],
    verb: ['attend habitualy.'],
    modification: ['fraquenter;', 'frequently.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fresco',
    adjective: [],
    adverb: [],
    noun: [
      'painting watercolour wall, ceiling plaster still wet;',
      'this method painting.',
    ],
    verb: [],
    modification: ['frescoed.'],
    idiom: [],
    image: '/images/fresco.png',
  },
  {
    word: 'fresh',
    adjective: [
      'newly made;',
      'not previously used;',
      'lately arrived;',
      'not stale;',
      'not preserved;',
      'pure, bright;',
      'alert;',
      'young.',
    ],
    adverb: ['newly.'],
    noun: [],
    verb: [],
    modification: ['freshly;', 'freshness;', 'freshen.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fresher',
    adjective: [],
    adverb: [],
    noun: [
      'freshman;',
      'first-year student university, college;',
      'high school.',
    ],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fret',
    adjective: [],
    adverb: [],
    noun: [],
    verb: [
      'destroy gradually, rubbing, corrosion, erosion;',
      'gnawing, rubbing;',
      'stale of anxiety.',
    ],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fretful',
    adjective: ['anxious, distressed, irritiated.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['fretfully;', 'fretfulness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fretwork',
    adjective: [],
    adverb: [],
    noun: ['ornamental work wood, fretsaw.'],
    verb: [],
    modification: [],
    idiom: [],
    image: '/images/fretwork.png',
  },
];
export default fraternalStack;