import { TListElement } from './stacks.types';

const friableStack: TListElement[] = [
  {
    word: 'friable',
    adjective: ['easily crumbled, powder.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'friar',
    adjective: [],
    adverb: [],
    noun: [
      'member, religious orders, mendicant, (Augustinians, Carmelites, Dominicans, Franciscans).',
    ],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fricassee',
    adjective: [],
    adverb: [],
    noun: ['dish, white meat, white sauce.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'friction',
    adjective: [],
    adverb: [],
    noun: [
      'resistance, object, surface, moving;',
      'clash, wills, temperaments, opinion;',
      'work, by frictional contact.',
    ],
    verb: [],
    modification: ['frictional;', 'frictionless.'],
    idiom: [],
    image: null,
  },
  {
    word: 'Friday',
    adjective: [],
    adverb: ['on Friday;', 'each Friday.'],
    noun: ['day.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fridge',
    adjective: [],
    adverb: [],
    noun: ['refrigerator.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fried',
    adjective: ['cooked, frying.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'friend',
    adjective: [],
    adverb: [],
    noun: [
      'person, mutual affection;',
      'person, ally, not, enemy;',
      'supporter, cause;',
      'acquaintance, person known casually.',
    ],
    verb: ['add to social network.'],
    modification: [],
    idiom: ['friends in high places: highly placed people, influence.'],
    image: null,
  },
  {
    word: 'friendly',
    adjective: ['acting, like, friend;', 'not, competitive.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['friendlily;', 'friendliness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frieze',
    adjective: [],
    adverb: [],
    noun: ['band, decoration, near, ceiling.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frigate',
    adjective: [],
    adverb: [],
    noun: ['warship, French, army.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fright',
    adjective: [],
    adverb: [],
    noun: ['sudden, extreme fear;', 'experience, causes one to feel.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frighten',
    adjective: [],
    adverb: [],
    noun: [],
    verb: ['scare.'],
    modification: ['frightener;', 'frightening;', 'frighteningly.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frightful',
    adjective: ['dreadful, shocking;', 'extremely bad.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['frightfully;', 'frightfulness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frigid',
    adjective: [
      'extremely cold;',
      'woman;',
      'unable;',
      'sexual, arousal, responsiveness;',
      'stiff, formal, behavior, style.',
    ],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['frigidity;', 'frigidly;', 'frigidness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frill',
    adjective: [],
    adverb: [],
    noun: [
      'material;',
      'natural fringe, hair, feathers, animal;',
      'additional extra, embellishment, decoration.',
    ],
    verb: ['decorate, frill.'],
    modification: ['frilled.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fringe',
    adjective: [],
    adverb: [],
    noun: [
      'bordering;',
      'front hair;',
      'outer edge, area, group, sphere;',
      'of secondary, importance.',
    ],
    verb: ['decorate, fringe;', 'serve, fringe to.'],
    modification: ['fringed;', 'fringeless;', 'fringy.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frisk',
    adjective: [],
    adverb: [],
    noun: ['act, frisking;', 'playful leap, skip.'],
    verb: [
      'search (a person), drugs, pass hands over, body, concealed weapon;',
      'leap, skip, playfully.',
    ],
    modification: ['frisker.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frisky',
    adjective: ['lively, playful;', 'full of energy.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['friskily;', 'friskiness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frisson',
    adjective: [],
    adverb: [],
    noun: ['emotional thrill, shiver, excitement, fear.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fritter',
    adjective: [],
    adverb: [],
    noun: [],
    verb: ['waste (money, time, energy), triflingly.'],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frivolous',
    adjective: ['not having serious purpose, value;', 'superficial, carefree.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['frivolity;', 'frivolously;', 'frivolousness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frizz',
    adjective: [],
    adverb: [],
    noun: ['frizzy hair.'],
    verb: ['form (hair), tight curls;', 'hair, curl tightly.'],
    modification: ['frizzy;', 'frizziness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frock',
    adjective: [],
    adverb: [],
    noun: ["woman's, girl's dress;", "monk's, priest's, gown."],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frog',
    adjective: [],
    adverb: [],
    noun: ['amphibians;', 'French, francophone person.'],
    verb: [],
    modification: [],
    idiom: ['frog in the throat, hoarseness.'],
    image: null,
  },
  {
    word: 'frogman',
    adjective: [],
    adverb: [],
    noun: ['scuba diver, police, military operations.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frolic',
    adjective: [],
    adverb: [],
    noun: [],
    verb: ['play, move, cheerfully, excitedly.'],
    modification: [
      'frolicker;',
      'frolicsome;',
      'frolicsomely;',
      'frolicsomeness.',
    ],
    idiom: [],
    image: null,
  },
  {
    word: 'from',
    adjective: [],
    adverb: [],
    // preposition: ['expressing separation, origin;', 'person, place, time;', 'avoided;', 'reason, cause;', 'distinguished;', 'lower limit;', 'position.'],
    noun: [
      'expressing separation, origin;',
      'person, place, time;',
      'avoided;',
      'reason, cause;',
      'distinguished;',
      'lower limit;',
      'position.',
    ],
    verb: [],
    modification: [],
    idiom: [
      'from now on, henceforward;',
      'from time to time, occasionally;',
      'from year to year, each year.',
    ],
    image: null,
  },
  {
    word: 'frond',
    adjective: [],
    adverb: [],
    noun: ['leaf, palm;', 'fern.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'front',
    adjective: ['of, the front.'],
    adverb: [],
    noun: [
      'side, nearer, towards, spectator;',
      'line, battle;',
      'foremost, position, actual fighting;',
      'bearing, composure, under threat;',
      'most, conspicuous position;',
      'outward appearance, show, cover;',
      'pretext;',
      'person, cover.',
    ],
    verb: ['lead, (band, organization).'],
    modification: ['frontward.'],
    idiom: [],
    image: null,
  }
];
export default friableStack;
