import { TListElement } from './stacks.types';

const frontageStack: TListElement[] = [
  {
    word: 'frontage',
    adjective: [],
    adverb: [],
    noun: ['front, building, lot.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frontal',
    adjective: ['of, at, on, front.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['frontally.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frontispiece',
    adjective: [],
    adverb: [],
    noun: ['illustration facing, title, book.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frost',
    adjective: [],
    adverb: [],
    noun: [
      'tiny white crystals, ground, temperature, below, freezing;',
      'period of cold weather;',
      'coolness of behaviour, temperament;',
      'cover, frost;',
      'cover, icing.',
    ],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frostbite',
    adjective: [],
    adverb: [],
    noun: ['injury, body tissues, intense cold, resulting, gangrene.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frosting',
    adjective: [],
    adverb: [],
    noun: ['icing, cake.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frosty',
    adjective: [
      'very cold, with frost;',
      'covered with, hoarfrost;',
      'unfriendly.',
    ],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['frostily;', 'frostiness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'froth',
    adjective: [],
    adverb: [],
    noun: [
      'collection, bubbles, liquid, shaking, fermenting, foam;',
      'anything, of little worth.',
    ],
    verb: ['emit froth.'],
    modification: ['frothily;', 'frothiness;', 'frothy.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frown',
    adjective: [],
    adverb: [],
    noun: ['act, frowning.'],
    verb: [
      'contract, eyebrows, wrinkle, forehead, anger, thought;',
      'glum, corners, mouth, down;',
      'express disapproval.',
    ],
    modification: ['frowner;', 'frowning;', 'frowningly.'],
    idiom: [],
    image: null,
  },
  {
    word: 'frozen',
    adjective: [
      'solidified, exposure, cold;',
      'preserved, refrigeration;',
      'emotionally frigid;',
      'credit, impossible, realize.',
    ],
    adverb: [],
    noun: [],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fructose',
    adjective: [],
    adverb: [],
    noun: ['sugar, honey, fruits.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'frugal',
    adjective: [
      'sparing or economical;',
      'plain, simple;',
      'avoidance, excess.',
    ],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['frugality;', 'frugally;', 'frugalness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fruit',
    adjective: [],
    adverb: [],
    noun: [
      'fleshy, product, plant, tree, containing seed;',
      'product, anything, produced, activity, work;',
      'male homosexual.',
    ],
    verb: ['bear, fruit.'],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fruiterer',
    adjective: [],
    adverb: [],
    noun: ['person, sells fruit.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fruitful',
    adjective: [
      'tree, producing much fruit;',
      'soil, fertile;',
      'producing good results;',
      'producing offspring, prolifically.',
    ],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['fruitfully;', 'fruitfulness.'],
    idiom: [],
    image: null,
  },
  {
    word: 'fruition',
    adjective: [],
    adverb: [],
    noun: ['bearing, fruit;', 'realization, aims, hopes, plans.'],
    verb: [],
    modification: [],
    idiom: [],
    image: null,
  },
  {
    word: 'fruitless',
    adjective: ['not bearing fruit.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: [
      'fruitlessly;',
      'fruitlessness;',
      'unproductive, achieve, desired results.',
    ],
    idiom: [],
    image: null,
  },
  {
    word: 'fruity',
    adjective: ['of, fruit, taste, smell;', 'voice, mellow, deep, rich.'],
    adverb: [],
    noun: [],
    verb: [],
    modification: ['fruitier, fruitiest;', 'fruitiness.'],
    idiom: [],
    image: null,
  },
];
export default frontageStack;
